server:
  port: 60010
spring:
  application:
    name: qq-gateway
  redis:
    host: 192.168.136.150
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.150:8848   #注册中心nacos地址
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: system
          uri: lb://qq-system-service
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: content
          uri: lb://qq-content-service
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1
logging:
  level:
    com.alibaba.nacos.client.*: WARN