server:
  port: 60030
  servlet:
    encoding:
      charset: UTF-8
#微服务启动参数
spring:
  application:
    name: qq-content-service
  redis:
    host: 152.32.252.204
    port: 6379
  cloud:
    nacos:
      discovery:      #配置注册中心
        server-addr: 192.168.136.150:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://152.32.252.204:3306/qq-content?userUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ofo12441200
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml
mybatis-plus:
  #别名包设置
  type-aliases-package: com.qiqu.*.domain
  # 映射文件mapper文件存储位置
  mapper-locations: classpath*:mappers/*.xml  #加载 mybatis 映射文件的位置
  global-config:
    db-config:
      id-type: auto # 注解策略
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql日志